Feature('Backend Functionality');

Scenario('Check Functionality Exit And Works Well', (I) => {
    I.loginAsAdmin();
    I.click('WP ERP');
            I.waitForElement('#wpbody-content');
            I.checkWarningFatalNotice();
                I.see('Overview');
                I.see('Latest Announcement');
                I.see('HR');
                I.see('CRM');
                I.see('Accounting');
                I.see('Latest ERP Blog');
    	I.click('HR');
            I.waitForElement('.erp-single-container');
            I.checkWarningFatalNotice();
                I.see('HR Management');
                I.see('Latest Announcement');
                I.see('My Leave Calendar');
                I.see('Celebrations');
                I.see('Who is out');
                I.see('About to end');
            // I.click('Employees');
            I.amOnPage('/erp-feature-extension/wp-admin/admin.php?page=erp-hr&section=employee');
                I.waitForElement('#wpbody');
                I.checkWarningFatalNotice();
                I.see('Employees');
            I.amOnPage('/erp-feature-extension/wp-admin/admin.php?page=erp-hr&section=department');
                I.waitForElement('#wpbody');
                I.checkWarningFatalNotice();
                I.see('Departments');
            I.amOnPage('/erp-feature-extension/wp-admin/admin.php?page=erp-hr&section=designation');
                I.waitForElement('#wpbody');
                I.checkWarningFatalNotice();
                I.see('Designation');
            I.amOnPage('/erp-feature-extension/wp-admin/edit.php?post_type=erp_hr_announcement');
                I.waitForElement('#wpbody');
                I.checkWarningFatalNotice();
                I.see('Announcement');
            I.amOnPage('/erp-feature-extension/wp-admin/admin.php?page=erp-hr&section=leave');
                I.waitForElement('#wpbody');
                I.checkWarningFatalNotice();
                I.see('Leave Requests');
            I.amOnPage('/erp-feature-extension/wp-admin/admin.php?page=erp-hr&section=report');
                I.waitForElement('#wpbody');
                I.checkWarningFatalNotice();
                I.see('Reports');
            I.amOnPage('/erp-feature-extension/wp-admin/admin.php?page=erp-hr&section=help');
                I.waitForElement('#wpbody');
                I.checkWarningFatalNotice();
                I.see('HRM Help');
    	I.click('CRM');
            I.waitForElement('.erp-single-container');
            I.checkWarningFatalNotice();
                I.see('CRM Dashboard');
                I.see("Today's Schedules");
                I.see('Customer Statistics');
                I.see("Today's Schedules");
                I.see('Upcoming Schedules');
                I.see('Recently Added');
                I.see('Total Inbound Emails');
            I.amOnPage('/erp-feature-extension/wp-admin/admin.php?page=erp-crm&section=contacts');
                I.waitForElement('#wpbody');
                I.checkWarningFatalNotice();
                I.see('Contact');
            I.amOnPage('/erp-feature-extension/wp-admin/admin.php?page=erp-crm&section=companies');
                I.waitForElement('#wpbody');
                I.checkWarningFatalNotice();
                I.see('Company');
            I.amOnPage('/erp-feature-extension/wp-admin/admin.php?page=erp-crm&section=activities');
                I.waitForElement('#wpbody');
                I.checkWarningFatalNotice();
                I.see('Activities');
            I.amOnPage('/erp-feature-extension/wp-admin/admin.php?page=erp-crm&section=schedules');
                I.waitForElement('#wpbody');
                I.checkWarningFatalNotice();
                I.see('Schedules');
                I.click('All Schedules');
            I.amOnPage('/erp-feature-extension/wp-admin/admin.php?page=erp-crm&section=contact-groups');
                I.waitForElement('#wpbody');
                I.checkWarningFatalNotice();
                I.see('Contact Groups');
            I.amOnPage('/erp-feature-extension/wp-admin/admin.php?page=erp-crm&section=reports');
                I.waitForElement('#wpbody');
                I.checkWarningFatalNotice();
                I.see('Reports');
            I.amOnPage('/erp-feature-extension/wp-admin/admin.php?page=erp-crm&section=help');
                I.waitForElement('#wpbody');
                I.checkWarningFatalNotice();
                I.see('CRM Help');
    	I.click('Accounting');
            I.waitForElement('#erp-accounting');
            I.checkWarningFatalNotice();
                I.see('Dashboard');
                I.see('Income & Expense');
                I.see('Accounts');
                I.see('Invoice payable to you');
                I.see('Bills you need to pay');
            I.amOnPage('/erp-feature-extension/wp-admin/admin.php?page=erp-accounting#/users');
                I.waitForElement('.app-customers');
                I.checkWarningFatalNotice();
                I.see('Customers');
            I.amOnPage('/erp-feature-extension/wp-admin/admin.php?page=erp-accounting#/transactions');
                I.waitForElement('.wperp-container');
                I.checkWarningFatalNotice();
                I.see('Sales Transactions');
            I.amOnPage('/erp-feature-extension/wp-admin/admin.php?page=erp-accounting#/charts');
                I.waitForElement('#erp-accounting');
                I.checkWarningFatalNotice();
                I.see('Chart of Accounts');
            I.amOnPage('/erp-feature-extension/wp-admin/admin.php?page=erp-accounting#/banks');
                I.waitForElement('#erp-accounting');
                I.checkWarningFatalNotice();
                I.see('Accounts');
            I.amOnPage('/erp-feature-extension/wp-admin/admin.php?page=erp-accounting#/products');
                I.waitForElement('.wperp-products');
                I.checkWarningFatalNotice();
                I.see('Products');
            I.amOnPage('/erp-feature-extension/wp-admin/admin.php?page=erp-accounting#/taxes');
                I.waitForElement('.app-taxes');
                I.checkWarningFatalNotice();
                I.see('Tax Rates');
            I.amOnPage('/erp-feature-extension/wp-admin/admin.php?page=erp-accounting#/reports');
                I.waitForElement('.reports-overview');
                I.checkWarningFatalNotice();
                I.see('Trial Balance');
                I.see('Ledger Report');
                I.see('Income Statement');
                I.see('Sales Tax');
                I.see('Balance Sheet');
            I.amOnPage('/erp-feature-extension/wp-admin/admin.php?page=erp-accounting#/erp-ac-help');
                I.waitForElement('#erp-accounting');
                I.checkWarningFatalNotice();
                I.see('Accounting Help');
    	I.click('Company');
            I.waitForElement('#wpbody-content');
            I.checkWarningFatalNotice();
    	I.click('Tools');
            I.waitForElement('.postbox');
            I.checkWarningFatalNotice();
            // I.see('Admin Menu');
            //     I.click('Import');
            //         I.waitForElement('.postbox');
            //     I.click('Export');
            //         I.waitForElement('.postbox');
            //     I.click('Misc.');
            //         I.waitForElement('.postbox');
            //     I.click('Status');
            //         I.waitForElement('.postbox');
            //     I.click('Audit Log');
            //         I.waitForElement('.postbox');
    	I.click('Modules');
            I.waitForElement('#wpbody-content');
            I.checkWarningFatalNotice();
            I.see('Modules');
    	I.click('Add-Ons');
            I.waitForElement('#wpbody-content');
            I.checkWarningFatalNotice();
            I.see('Add-ons');
    	I.click('Settings');
            I.waitForElement('#mainform');
            I.checkWarningFatalNotice();
            // I.see('General Options');
            //     I.click('Emails');
            //         I.waitForElement('#mainform');
            //     I.click('HR');
            //         I.waitForElement('#mainform');
            //     I.click('Contact Forms');
            //         I.waitForElement('#mainform');
            //     I.click('CRM');
            //         I.waitForElement('#mainform');
            //     I.click('Accounting');
            //         I.waitForElement('#mainform');
    
});
